### ISSUE TITLE
`make-based`: Add `do.sh` script for helloworld C++

### ISSUE THREAD

**Issue by razvand** [unikraft-upb/scripts#11]
Add a `do.sh` build script on the [`make-based/` directory](https://github.com/unikraft-upb/scripts/tree/main/make-based) for [`app-helloworld-cpp`](https://github.com/unikraft/app-helloworld-cpp), similar to the existing ones for `app-helloworld`, `app-httpreply` and `app-nginx`.

See the existing [Musl-based scripts and README](https://github.com/unikraft-upb/scripts/tree/main/musl).

Make sure you validate the script with [`shellcheck`](https://www.shellcheck.net/).

**Hackathon points**: 20

**Comment by KonosSgouras** [comment]
Working on this

**Comment by panosmaurikos** [comment]
working on this!!!

**Comment by KonosSgouras** [comment]
finished
