### ISSUE TITLE
`make-based`: Add `do.sh` script for Python

### ISSUE THREAD

**Issue by razvand** [unikraft-upb/scripts#12]
Add a `do.sh` build script on the [`make-based/` directory](https://github.com/unikraft-upb/scripts/tree/main/make-based) for [`app-python3`](https://github.com/unikraft/app-python3), similar to the existing ones for `app-helloworld`, `app-httpreply` and `app-nginx`.

See the existing [Musl-based scripts and README](https://github.com/unikraft-upb/scripts/tree/main/musl).

Make sure you validate the script with [`shellcheck`](https://www.shellcheck.net/).

**Hackathon points**: 20

**Comment by FotisKouzinos** [comment]
!

**Comment by akouk** [comment]
Working on this.

**Comment by StefanJum** [comment]
Closed by #23
