### ISSUE TITLE
`make-based`: Add `do.sh` script for Micropython

### ISSUE THREAD

**Issue by razvand** [unikraft-upb/scripts#13]
Add a `do.sh` build script on the [`make-based/` directory](https://github.com/unikraft-upb/scripts/tree/main/make-based) for [`app-micropython`](https://github.com/unikraft/app-micropython), similar to the existing ones for `app-helloworld`, `app-httpreply` and `app-nginx`.

See the existing [Musl-based scripts and README](https://github.com/unikraft-upb/scripts/tree/main/musl).

Make sure you validate the script with [`shellcheck`](https://www.shellcheck.net/).

**Hackathon points**: 20

**Comment by adamkapetis** [comment]
working on this

**Comment by dondavan** [comment]
working on this
