### ISSUE TITLE
`make-based`: Add `do.sh` build script for Redis

### ISSUE THREAD

**Issue by razvand** [unikraft-upb/scripts#9]
Add a `do.sh` build script for [`app-redis`](https://github.com/unikraft/app-redis), similar to the existing ones for `app-helloworld`, `app-httpreply` and `app-nginx`.

**Hackathon points**: 20

**Comment by StefanosChelas** [comment]
I want to take it.

**Comment by StefanJum** [comment]
Closed by #22
